config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
    validates :title, presence: true, length: { in: 1..140 }
    validates :content, presence: true, length: { in: 1..500 }
    validates :image, presence: true

    belongs_to :user

    mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_validation { email.downcase! } 

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :pictures

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [:new, :create]

  def index
    @pictures = Picture.all
  end

  def show
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end


  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end

  def logged_in?
    if current_user.nil?
      redirect_to new_session_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id)
      else
        flash.now[:danger] = 'ログインに失敗しました'
        render 'new'
      end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
  end

  def create
   @user = User.new(user_params)
    if @user.save
     redirect_to user_path(@user.id)
     else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

   def user_params
     params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
       @current_user ||= User.find_by(id: session[:user_id]) 
    end
    
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebookclone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <div class="login_container">
        <div class="login_container_lfoat">
          <h1><%= link_to "facebook-clone", new_user_path %></h1>
        </div>
        <div class="login_container_rfloat">
              <ul>
                <% if logged_in? %>
                  <li class="menus"><%= link_to "#{current_user.name}", user_path(current_user.id) %></li>
                  <li class="menus"><%= link_to "投稿一覧", pictures_path %></li>
                  <li class="menus"><%= link_to "新規投稿", new_picture_path %></li>
                  <li class="menus"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
                <% else %>
                  <li class="menus"><%= link_to "新規登録", new_user_path %></li>
                  <li class="menus"><%= link_to "ログイン", new_session_path %></li>
                <% end %>
              </ul>
        </div>
      </div>
    </header>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :picture_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :picture_content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image, id: :picture_image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<div class="content">
  <div class="container">

    <h3>以下の内容で、送信する。</h3>

    <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>

      <p>Content:<%= @picture.content %></p>
        <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
        <%= form.hidden_field :image_cache %>
      <div class="confirm_submit">
        <%= form.submit  "投稿する" %>
      </div>
    <% end %>

    <%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image_cache %>
      <div class="confirm_submit">
      <%= form.submit "戻る", name: 'back' %>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="content">
  <div class="container">

    <h1>編集画面</h1>

    <%= render 'form', picture: @picture %>

    <%= link_to '詳細', @picture, class:"operation_button" %>
    <%= link_to '戻る', pictures_path, class:"operation_button" %>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="content">
  <div class="container">
      <h1>投稿一覧</h1>
        <table>
          <thead>
            <div class="index"
            <tr>
              <th>投稿者</th>
              <th>タイトル</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @pictures.each do |picture| %>
              <tr>
                <td><%= link_to(picture.user.name, user_path(picture.user.id)) %></td>
                <td><%= link_to(picture.title, picture_path(picture.id)) %>
                <td><%= link_to '詳細', picture %></td>
                <td><%= link_to '編集', edit_picture_path(picture) %></td>
                <td><%= link_to '削除', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
<br>

      <%= link_to '新規投稿作成', new_picture_path, class:"operation_button" %>

  </div>
</div>

app/views/pictures/new.html.erb
<div class="content">
  <div class="container">

<h1>新規投稿</h1>

<%= render 'form', picture: @picture %>

<%= link_to '新規投稿へ戻る', pictures_path, class:"operation_button" %>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="content">
  <div class="container">
    <p>
      <strong>contributor:</strong>
      <%= @picture.user.name %>
    </p>
    <p>
      <strong>Title:</strong>
      <%= @picture.title %>
    </p>
    <p>
      <strong>Content:</strong>
      <%= @picture.content %>
    </p>
    <p>
      <strong>Image:</strong>
      <%= image_tag @picture.image.url %>
    </p>
    <%= link_to '編集', edit_picture_path(@picture) , class:"operation_button" %>
    <%= link_to '戻る', pictures_path , class:"operation_button" %>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<div class="content">
  <div class="container">

      <div class="lfloat">
        <div class="top_context">
            <p>Facebook-cloneを使っても、友達や同僚、同級生、仲間たちとつながりを深められません。ケータイ、スマートフォンからもアクセスできます？</p>
              <img class="top_img" src="/facebook_hom.jpg">
        </div>
      </div>
    <div class="rfloat">
      <div class="registration_container">
        <div id="registration_top">
            <h1>アカウント登録</h1>
            <p>情報のプライバシーは設定で管理できるので多分安心です。</p>
        </div>
            <div class="reg_form_box">
              <%= form_with(model: @user, local: true) do |f| %>
              <div class="name_form_box mbm">
                <%= f.text_field :name, placeholder: "名前" %>
              </div>
              <div class="email_form_box mbm">
                <%= f.email_field :email, placeholder: "メールアドレス" %>
              </div>
              <div class="password_form_box mbm">
                <%= f.password_field :password, placeholder: "パスワード" %>
              </div>
              <div class="password_confirmation_form_box mbm">
                <%= f.password_field :password_confirmation, placeholder: "パスワード(確認用)" %>
              </div>
                <div class="account_submit">
                  <%= f.submit "アカウント登録" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>